# db-credentials-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials-secret # Must match the name referenced in the Deployment
type: Opaque
data:
  # Base64 encoded: 'batchuser'
  username: YmF0Y2h1c2Vy

  # Base64 encoded: 'mysecurepassword'
  password: bXlzZWN1cmVwYXNzd29yZA==